site_name: "Portfolio"
theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    # - navigation.expand
    - content.code.annotate
    - content.tabs.link
  palette:
    - scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      fallback_to_build_date: true
  - glightbox
  - mkdocs-jupyter:
      execute: false
      include_source: true
      include: ["*.ipynb"]  

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Inicio: index.md
  - Acerca de mÃ­: acerca.md
  - Recursos: recursos.md
  - Portafolio:
      - IngenierÃ­a de Datos:
          - "ğŸ§­ UT1 â€“ ExploraciÃ³n y Fuentes de Datos":
              - IntroducciÃ³n: portfolio/ingenieria_datos/UT1/Portada.md
              - ğŸŒ¸ Mirada analÃ­tica al clÃ¡sico Iris; separando especies con datos: portfolio/ingenieria_datos/UT1/01-exploracion-iris.md
              - ğŸ¬ Netflix bajo la lupa; explorando tendencias globales de contenido: portfolio/ingenieria_datos/UT1/03-eda-netflix.md
              - ğŸ”— Uniendo mundos de datos; anÃ¡lisis multifuente con merges y joins: portfolio/ingenieria_datos/UT1/04-eda-multifuentesyjoins.md
              - ğŸŒ Proyecto extra; Explorando datos meteorolÃ³gicos desde una API (Open-Meteo): portfolio/ingenieria_datos/UT1/Extra.md
          - "ğŸ§­ UT2 â€“ Calidad y Ã‰tica de los Datos":
              - IntroducciÃ³n: portfolio/ingenieria_datos/UT2/Portada.md
              - ğŸ•µï¸ DetecciÃ³n de valores faltantes; jugando al detective de datos: portfolio/ingenieria_datos/UT2/05-missing-data-detective.md
              - ğŸ  Escalando variables con estilo; creando pipelines justos y reproducibles: portfolio/ingenieria_datos/UT2/06-feature-scaling&pipelines.md
              - âš–ï¸ Modelos mÃ¡s justos; detectando y mitigando sesgos en Boston, Titanic y Ames: portfolio/ingenieria_datos/UT2/07-deteccion-sesgo.md
              - ğŸ¬ Proyecto extra; AuditorÃ­a de calidad y joins con TMDb 5000 (movies & credits): portfolio/ingenieria_datos/UT2/Extra.md
          - "ğŸ§­ UT3 - Feature Engineering":
              - IntroducciÃ³n: portfolio/ingenieria_datos/UT3/Portada.md
              - ğŸ§© IngenierÃ­a de Features; mejorando el modelo de Ames Housing: portfolio/ingenieria_datos/UT3/08-feature-engineering.md
              - ğŸ§© Encoding Avanzado; experimentando con cardinalidad, fuga y explicabilidad: portfolio/ingenieria_datos/UT3/09-encoding.md
              - ğŸ§  ReducciÃ³n y SelecciÃ³n; comparando PCA y tÃ©cnicas de Feature Selection en Ames: portfolio/ingenieria_datos/UT3/10-PCAFeature-selection.md
              - â±ï¸ Tiempo en AcciÃ³n; creando y evaluando features temporales con Pandas: portfolio/ingenieria_datos/UT3/11-Temporal-feature-engineering.md
              - ğŸ§¬ Proyecto extra; Mini-Assignment, comparando robustez de PCA vs Selection en pipelines reales: portfolio/ingenieria_datos/UT3/Extra.md
          - "ğŸ§­ UT4 - Datos Especiales":
              - IntroducciÃ³n: portfolio/ingenieria_datos/UT4/Portada.md
              - ğŸŒ Manejo de Datos Geoespaciales; visualizaciÃ³n y anÃ¡lisis con GeoPandas y Folium: portfolio/ingenieria_datos/UT4/12-geoespacial_geopandas.md
              - ğŸ“¸ Preprocesamiento de ImÃ¡genes; mejorando calidad y extracciÃ³n de features visuales: portfolio/ingenieria_datos/UT4/13-preprocesamiento_img.md
              - ğŸ”Š Procesamiento de Audio; limpieza y extracciÃ³n de caracterÃ­sticas acÃºsticas con Librosa: portfolio/ingenieria_datos/UT4/14-procesamiento_audio.md